### ISSUE TITLE
As a student I want to be able to search posts based on the groups/classes.

### ISSUE THREAD

**Issue by xavier-xia-99** [CMU-313/fall23-nodebb-op#2]

**Comment by yliang412** [comment]
Here are some initial thoughts on the technical requirements for this user story.

### Search based on the current search implementation of NodeBB

- add `class` into the data model of the post.
- properly handle old posts that do not have the `class` attribute.
- implement filter based on the `class` attribute
- add filter drop down for a user (could show all classes the user is in)

### Search based on a new class specific home page

Alternatively, we could create an entire different UI for a class home page and do search within the class based on that. This would require more effort and the estimate is that this would take more than a single person to implement. However, it does provide students and instructors a better interface, since materials from different classes rarely fit together.

**Comment by PeterNotFound114** [comment]
I would say that we only need to add class attribute and filter based on that. It is not necessary to create entirely different UIs for class homepage, as the current UI of NodeBB suffices for displaying posts with a search bar. We just need a different ordering schema for the posts (i.e., chronological or by class) when we display posts initially.

**Comment by PeterNotFound114** [comment]
Here's a list of the documents that we might need to change when we implement this feature (as from what I can currently see):
**For Post Data Model:**
Create Posts: (add fields) posts/create.js
Modify Posts: (add fields) posts/data.js
Post Summary (add fields) posts/summary.js

**For Process logic for searching:** 
	Query Params: controllers/search.js (showAsClass need to be implemented)
	Ordering / Search Process: src/search.js (implement datashow by class)

**Comment by PeterNotFound114** [comment]
Need to add group_id to topics so that all posts belonging to that topic will automatically belong to the group.

**Comment by PeterNotFound114** [comment]
When creating the topic, we need to add a box next to the category that specifies which group the topic belongs.
